Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -17,8 +17,9 @@ jobs:
       - name: Build Docker image
         run: |
           docker build -t discord-bot:latest .
-          docker save discord-bot:latest > /tmp/discord-bot.tar
-
+          docker save discord-bot:latest > discord-bot.tar
+          ls -la discord-bot.tar
+          
       - name: Copy Docker image to VPS
         uses: appleboy/scp-action@master
         with:
@@ -27,9 +28,8 @@ jobs:
           password: ${{ secrets.SSH_PASS }}
           key: ${{ secrets.SSHKEY }}
           port: ${{ secrets.PORT }}
-          source: "/tmp/discord-bot.tar"
+          source: "discord-bot.tar"
           target: "/tmp/"
-          strip_components: 1
 
       - name: Deploy to VPS
         uses: appleboy/ssh-action@master
@@ -51,23 +51,30 @@ jobs:
               git clone https://github.com/${{ github.repository }}.git .
             fi
             
-            # Загружаем образ из tar файла
-            docker load < /tmp/discord-bot.tar
-            
-            # Останавливаем и удаляем старый контейнер, если он существует
-            docker stop discord-bot || true
-            docker rm discord-bot || true
-            
-            # Запускаем новый контейнер с монтированием конфигурационных файлов
-            docker run -d \
-              --name discord-bot \
-              --restart unless-stopped \
-              -v ~/discord-bot/.env:/app/.env \
-              -v ~/discord-bot/config.toml:/app/config.toml \
-              discord-bot:latest
-            
-            # Удаляем tar файл
-            rm /tmp/discord-bot.tar
-            
-            # Удаляем неиспользуемые образы
-            docker image prune -f
+             # Проверяем наличие файла
+            if [ -f "/tmp/discord-bot.tar" ]; then
+                echo "Docker image found, loading..."
+                # Загружаем образ из tar файла
+                docker load < /tmp/discord-bot.tar
+                
+                # Останавливаем и удаляем старый контейнер, если он существует
+                docker stop discord-bot || true
+                docker rm discord-bot || true
+                
+                # Запускаем новый контейнер с монтированием конфигурационных файлов
+                docker run -d \
+                  --name discord-bot \
+                  --restart unless-stopped \
+                  -v ~/discord-bot/.env:/app/.env \
+                  -v ~/discord-bot/config.toml:/app/config.toml \
+                  discord-bot:latest
+                
+                # Удаляем tar файл
+                rm /tmp/discord-bot.tar
+                
+                # Удаляем неиспользуемые образы
+                docker image prune -f
+            else
+                echo "Error: Docker image file not found in /tmp/discord-bot.tar"
+                exit 1
+            fi
